version: "3"

tasks:
  generate:pb:
    cmds:
      - | 
        protoc -I ./proto --go_out=paths=source_relative:./gen --go_opt=M=proto/*.proto=gen \
        --go-grpc_out=./gen --go-grpc_opt=paths=source_relative ./proto/*.proto 
  
  dockerize:hello-world:
    cmds:
      - | 
        docker build -t hello-world-extension ./examples/hello-world

  dockerize:math:multi-arch:
    cmds:
      - |
        docker buildx build --push \
        --platform linux/arm64/v8,linux/amd64 \
        --tag kwildb/extension-math:multi-arch \
        ./examples/math